# List available receipes
@list:
  just --list

{%- if cookiecutter.submit_strategy == "Use hydra plugin" -%}
{% raw %}

# Submit slurm job
submit partition max_parallel_jobs repeats experiment_group="test":
  #!/bin/bash
  set -e  # Stop on first failure{% endraw %}

  python -m {{cookiecutter.package_name}}.run \
    {% raw %}hydra.launcher.partition={{partition}} \
    seed=range\(0,{{repeats}}\) \
    experiment_group={{experiment_group}} \
    hydra.launcher.max_jobs={{max_parallel_jobs}} \
    --config-name run_slurm \
    --multirun{% endraw %}
{% endif %}
